import {
  brandTitle,
  cyan,
  dim,
  divider,
  eventLine,
  hint,
  red,
  sectionTitle,
  statusError,
  statusPending,
  statusSuccess,
  yellow,
} from '@manicjs/tui';
import { existsSync } from 'fs';
import { loadConfig } from '../../config';
import { build } from './build';

/**
 * Deploys the built Manic application to configured providers.
 *
 * Builds the application first if needed, then runs provider-specific
 * build hooks and generates deploy commands. Use --run or -r flag to
 * execute deploy commands automatically.
 *
 * @example
 * // Show deploy commands without running
 * await deploy();
 *
 * @example
 * // Build and deploy automatically
 * await deploy(); // with --run flag
 *
 * @example
 * // Used via CLI
 * // manic deploy --run
 */
export async function deploy() {
  const config = await loadConfig();
  const providers = config.providers ?? [];

  if (providers.length === 0) {
    console.log(`\n${statusError('No providers configured in manic.config.ts')}`);
    console.log(dim('Add a provider to deploy:'));
    console.log(cyan('\n  import { vercel } from "@manicjs/providers";\n'));
    console.log(dim('  providers: [vercel()]'));
    process.exit(1);
  }

  const shouldRun =
    process.argv.includes('--run') || process.argv.includes('-r');
  const providerNames = providers.map(p => p.name).join(', ');
  console.log(`\n${brandTitle('deploy')}`);
  console.log(divider());
  console.log(sectionTitle('Deployment Session', 'production'));
  console.log(`  ${hint('Providers:', providerNames)}`);
  console.log(`  ${hint('Mode:', shouldRun ? 'run' : 'preview')}`);
  console.log(divider());

  const dist = config.build?.outdir ?? '.manic';
  if (!existsSync(dist)) {
    console.log(statusPending('Build output missing, running build first...'));
    await build();
    console.log(dim('│'));
  }

  const projectName =
    config.app?.name?.toLowerCase().replace(/\s+/g, '-') ?? 'manic-app';

  const deployCommands: Record<
    string,
    { configFile: string | null; command: string }
  > = {
    vercel: {
      configFile: 'vercel.json',
      command: 'bunx vercel deploy',
    },
    cloudflare: {
      configFile: null, // wrangler.toml is generated by the provider build
      command: `bunx wrangler pages deploy dist --project-name ${projectName}`,
    },
    netlify: {
      configFile: 'netlify.toml',
      command: 'bunx netlify deploy --prod',
    },
  };

  for (const provider of providers) {
    console.log(eventLine('deploy', `provider ${provider.name}`, 'info'));

    const deployInfo = deployCommands[provider.name];
    if (!deployInfo) {
      console.log(
        eventLine(
          'deploy',
          `unknown provider "${provider.name}", run deployment manually`,
          'warn'
        )
      );
      continue;
    }

    if (deployInfo.configFile && !existsSync(deployInfo.configFile)) {
      console.log(statusPending(`Generating ${deployInfo.configFile}...`));

      if (provider.name === 'vercel') {
        const vercelConfig = {
          buildCommand: 'bun run build',
          installCommand: 'bun install',
          framework: null,
        };
        await Bun.write('vercel.json', JSON.stringify(vercelConfig, null, 2));
      } else if (provider.name === 'netlify') {
        const netlifyToml = `[build]
  command = "bun run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "none"

# API routes -> serverless function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
`;
        await Bun.write('netlify.toml', netlifyToml);
      }

      console.log(statusSuccess(`Generated ${deployInfo.configFile}`));
    }

    console.log(`  ${hint('Command:', deployInfo.command)}`);

    if (shouldRun) {
      console.log(statusPending(`Running ${provider.name} deploy...`));
      const proc = Bun.spawn(deployInfo.command.split(' '), {
        stdio: ['inherit', 'inherit', 'inherit'],
        cwd: process.cwd(),
      });
      const code = await proc.exited;
      if (code === 0) {
        console.log(statusSuccess(`${provider.name} deploy completed`));
      } else {
        console.log(statusError(`${provider.name} deploy failed (exit ${code})`));
      }
    } else {
      console.log(eventLine('deploy', `preview only for ${provider.name}`, 'info'));
    }
    console.log(dim('│'));
  }

  if (!shouldRun) {
    console.log(yellow('\nAdd --run or -r flag to execute the deploy commands automatically.\n'));
  }
}
