import { loadConfig } from '../../config';
import { existsSync, watch } from 'fs';
import {
  brandTitle,
  cyan,
  debugLog,
  dim,
  divider,
  eventLine,
  hint,
  sectionTitle,
} from '@manicjs/tui';
import { platform } from 'node:os';
import { forceReleasePort, resolvePortConflict } from '../lib/port';
import { stopSubprocessTree } from '../lib/process';

/**
 * Options for the dev command
 * @interface DevOptions
 */
interface DevOptions {
  /** Port number to run the development server on */
  port?: number;
  /** Whether to expose the server to the network (0.0.0.0) */
  network?: boolean;
}

/**
 * Generates bunfig.toml by merging plugin bunfig snippets
 * @param plugins - Array of Manic plugins with bunfig configurations
 * @internal
 */
async function writeBunfig(plugins: NonNullable<Awaited<ReturnType<typeof loadConfig>>['plugins']>) {
  const serveStaticPlugins: string[] = [];
  const otherSnippets: string[] = [];

  const resolveServeStaticPlugin = (specifier: string): string => {
    const clean = specifier.replace(/^["']|["']$/g, '');
    try {
      // First try project-local resolution (expected for app dependencies)
      return Bun.resolveSync(clean, process.cwd());
    } catch {
      try {
        // Fallback: resolve relative to manic CLI package dependencies
        return Bun.resolveSync(clean, import.meta.dir);
      } catch {
        // Last fallback: keep original specifier
        return clean;
      }
    }
  };

  for (const plugin of plugins) {
    if (!plugin.bunfig) continue;
    const match = plugin.bunfig.match(/\[serve\.static\]\s*\nplugins\s*=\s*\[([^\]]+)\]/);
    if (match) {
      serveStaticPlugins.push(
        ...match[1]
          .split(',')
          .map(s => s.trim())
          .filter(Boolean)
          .map(resolveServeStaticPlugin)
      );
    } else {
      otherSnippets.push(plugin.bunfig);
    }
  }

  const sections: string[] = ['# Auto-generated by manic dev — do not edit'];
  if (serveStaticPlugins.length) {
    const serialized = serveStaticPlugins.map(v => JSON.stringify(v)).join(', ');
    sections.push(`[serve.static]\nplugins = [${serialized}]`);
  }
  sections.push(...otherSnippets);

  if (sections.length > 1) {
    await Bun.write(`${process.cwd()}/bunfig.toml`, sections.join('\n\n') + '\n');
  }
}

/**
 * Starts the Manic development server with hot module replacement (HMR).
 * Watches for config changes and automatically restarts the server.
 *
 * @param options - Dev server configuration options
 * @param options.port - Port to run the dev server on (default: 6070 or config value)
 * @param options.network - Whether to expose to network (0.0.0.0)
 *
 * @example
 * // Start dev server on default port
 * await dev({});
 *
 * @example
 * // Start on custom port with network exposure
 * await dev({ port: 3000, network: true });
 *
 * @example
 * // Used via CLI
 * // manic dev --port 3000 --network
 */
export async function dev({ port, network }: DevOptions): Promise<void> {
  const cwd = process.cwd();
  const openBrowser = (url: string): void => {
    const os = platform();
    if (os === 'win32') {
      Bun.spawn(['cmd', '/c', 'start', '', url], {
        stdout: 'ignore',
        stderr: 'ignore',
      }).unref();
      return;
    }
    const opener = os === 'darwin' ? 'open' : 'xdg-open';
    Bun.spawn([opener, url], { stdout: 'ignore', stderr: 'ignore' }).unref();
  };

  const loadAndSpawn = async () => {
    // Invalidate config cache by deleting the cached module
    const { cachedConfig } = await import('../../config') as any;
    if (cachedConfig !== undefined) {
      // Reset by re-importing with bust
      const { loadConfig: load } = await import(`../../config?t=${Date.now()}`);
      const config = await load(cwd);
      return { config };
    }
    const config = await loadConfig(cwd);
    return { config };
  };

  let config = await loadConfig(cwd);
  debugLog('dev', `loaded config from ${cwd}`);
  let initialPort = port ?? config.server?.port ?? 6070;
  const initialHost = network ? '0.0.0.0' : 'localhost';
  initialPort = await resolvePortConflict('dev', initialPort, '0.0.0.0');
  debugLog(
    'dev',
    `resolved startup host=${initialHost} port=${initialPort} network=${Boolean(network)}`
  );
  const printBanner = () => {
    console.log(`\n${brandTitle('dev')}`);
    console.log(divider());
    console.log(sectionTitle('Development Session', 'dev'));
    console.log(`  ${hint('URL:', `http://${initialHost === '0.0.0.0' ? 'localhost' : initialHost}:${initialPort}`)}`);
    console.log(`  ${hint('Host:', initialHost)}`);
    console.log(`  ${hint('HMR:', config.server?.hmr === false ? 'off' : 'on')}`);
    const mcpPlugin = config.plugins?.find(p => p.name === '@manicjs/mcp');
    if (mcpPlugin) {
      const mcpPath = (mcpPlugin as any).path ?? '/mcp';
      const base = `http://${initialHost === '0.0.0.0' ? 'localhost' : initialHost}:${initialPort}`;
      console.log(`  ${hint('MCP:', `${base}${mcpPath}`)}`);
    }
    console.log(
      `  ${dim('Keys:')} ${cyan('[b]')} ${dim('browser')}  ${cyan('[r]')} ${dim(
        'restart'
      )}  ${cyan('[c]')} ${dim('clear logs')}  ${cyan('[q]')} ${dim('quit')}`
    );
    console.log(divider());
  };

  printBanner();

  const spawn = async (cfg: typeof config) => {
    const finalPort = initialPort;
    const host = network ? '0.0.0.0' : 'localhost';
    const env = {
      ...process.env,
      PORT: finalPort.toString(),
      HOST: host,
      NETWORK: network ? 'true' : 'false',
      MANIC_TUI_SUPPRESS_SERVER_INFO: '1',
    };

    const preloads = (cfg.plugins ?? [])
      .flatMap(p => p.preload ? ['--preload', p.preload] : []);
    await writeBunfig(cfg.plugins ?? []);
    debugLog(
      'dev',
      `spawning bun watcher with ${preloads.length / 2} preload plugin(s) on port ${finalPort}`
    );

    return Bun.spawn(['bun', '--watch', '--no-clear-screen', ...preloads, '~manic.ts'], {
      stdout: 'inherit',
      stderr: 'inherit',
      stdin: 'ignore',
      env,
    });
  };

  let proc = await spawn(config);
  const state = {
    port: initialPort,
    host: initialHost,
  };

  // Watch manic.config.ts — restart server on change
  const configFile = ['manic.config.ts', 'manic.config.js'].find(f => existsSync(`${cwd}/${f}`));
  if (configFile) {
    let debounce: ReturnType<typeof setTimeout> | null = null;
    watch(`${cwd}/${configFile}`, () => {
      if (debounce) clearTimeout(debounce);
      debounce = setTimeout(async () => {
        console.log(`\n${eventLine('dev', 'manic.config changed, restarting...', 'warn')}`);
        proc.kill();
        // Re-import config fresh (bust module cache via timestamp)
        const mod = await import(`${cwd}/${configFile}?t=${Date.now()}`);
        config = mod.default ?? mod;
        debugLog('dev', `reloaded config module from ${configFile}`);
        proc = await spawn(config);
        state.port = initialPort;
        state.host = network ? '0.0.0.0' : 'localhost';
        console.log(eventLine('dev', 'server restarted with updated config', 'success'));
      }, 100);
    });
  }

  let keyListener: ((data: Buffer) => void) | null = null;
  const hadRawMode = process.stdin.isRaw;
  if (process.stdin.isTTY) {
    process.stdin.setRawMode?.(true);
    process.stdin.resume();
    keyListener = async (data: Buffer) => {
      const key = data.toString('utf8').toLowerCase();
      if (key === '\u0003' || key === 'q') {
        console.log(`\n${eventLine('dev', 'stopping dev server', 'warn')}`);
        await stopSubprocessTree(proc);
        await forceReleasePort(state.port);
        process.exit(0);
      }
      if (key === 'b') {
        const displayHost = state.host === '0.0.0.0' ? 'localhost' : state.host;
        const url = `http://${displayHost}:${state.port}`;
        openBrowser(url);
        debugLog('dev', `open browser requested for ${url}`);
        console.log(eventLine('dev', `opened ${url}`, 'info'));
      }
      if (key === 'r') {
        console.log(eventLine('dev', 'manual restart requested', 'warn'));
        await stopSubprocessTree(proc);
        await forceReleasePort(state.port);
        config = await loadConfig(cwd);
        proc = await spawn(config);
        state.port = initialPort;
        state.host = network ? '0.0.0.0' : 'localhost';
        console.log(eventLine('dev', 'server restarted', 'success'));
      }
      if (key === 'c') {
        debugLog('dev', 'clear logs requested');
        console.clear();
        printBanner();
      }
    };
    process.stdin.on('data', keyListener);
  }

  const cleanup = (): void => {
    (async () => {
      if (keyListener) process.stdin.off('data', keyListener);
      if (process.stdin.isTTY) process.stdin.setRawMode?.(hadRawMode ?? false);
      await stopSubprocessTree(proc);
      await forceReleasePort(state.port);
      process.exit();
    })();
  };

  process.on('SIGINT', cleanup);
  process.on('SIGTERM', cleanup);

  await proc.exited;
}
