import { loadConfig } from '../../config';
import { existsSync, watch } from 'fs';

/**
 * Options for the dev command
 * @interface DevOptions
 */
interface DevOptions {
  /** Port number to run the development server on */
  port?: number;
  /** Whether to expose the server to the network (0.0.0.0) */
  network?: boolean;
}

/**
 * Generates bunfig.toml by merging plugin bunfig snippets
 * @param plugins - Array of Manic plugins with bunfig configurations
 * @internal
 */
async function writeBunfig(plugins: NonNullable<Awaited<ReturnType<typeof loadConfig>>['plugins']>) {
  const serveStaticPlugins: string[] = [];
  const otherSnippets: string[] = [];

  for (const plugin of plugins) {
    if (!plugin.bunfig) continue;
    const match = plugin.bunfig.match(/\[serve\.static\]\s*\nplugins\s*=\s*\[([^\]]+)\]/);
    if (match) {
      serveStaticPlugins.push(...match[1].split(',').map(s => s.trim()).filter(Boolean));
    } else {
      otherSnippets.push(plugin.bunfig);
    }
  }

  const sections: string[] = ['# Auto-generated by manic dev — do not edit'];
  if (serveStaticPlugins.length) {
    sections.push(`[serve.static]\nplugins = [${serveStaticPlugins.join(', ')}]`);
  }
  sections.push(...otherSnippets);

  if (sections.length > 1) {
    await Bun.write(`${process.cwd()}/bunfig.toml`, sections.join('\n\n') + '\n');
  }
}

/**
 * Starts the Manic development server with hot module replacement (HMR).
 * Watches for config changes and automatically restarts the server.
 *
 * @param options - Dev server configuration options
 * @param options.port - Port to run the dev server on (default: 6070 or config value)
 * @param options.network - Whether to expose to network (0.0.0.0)
 *
 * @example
 * // Start dev server on default port
 * await dev({});
 *
 * @example
 * // Start on custom port with network exposure
 * await dev({ port: 3000, network: true });
 *
 * @example
 * // Used via CLI
 * // manic dev --port 3000 --network
 */
export async function dev({ port, network }: DevOptions): Promise<void> {
  const cwd = process.cwd();

  const loadAndSpawn = async () => {
    // Invalidate config cache by deleting the cached module
    const { cachedConfig } = await import('../../config') as any;
    if (cachedConfig !== undefined) {
      // Reset by re-importing with bust
      const { loadConfig: load } = await import(`../../config?t=${Date.now()}`);
      const config = await load(cwd);
      return { config };
    }
    const config = await loadConfig(cwd);
    return { config };
  };

  let config = await loadConfig(cwd);

  const spawn = async (cfg: typeof config) => {
    const finalPort = port ?? cfg.server?.port ?? 6070;
    const host = network ? '0.0.0.0' : 'localhost';
    const env = {
      ...process.env,
      PORT: finalPort.toString(),
      HOST: host,
      NETWORK: network ? 'true' : 'false',
    };

    await writeBunfig(cfg.plugins ?? []);

    const preloads = (cfg.plugins ?? [])
      .flatMap(p => p.preload ? ['--preload', p.preload] : []);

    return Bun.spawn(['bun', '--watch', ...preloads, '~manic.ts'], {
      stdout: 'inherit',
      stderr: 'inherit',
      stdin: 'inherit',
      env,
    });
  };

  let proc = await spawn(config);

  // Watch manic.config.ts — restart server on change
  const configFile = ['manic.config.ts', 'manic.config.js'].find(f => existsSync(`${cwd}/${f}`));
  if (configFile) {
    let debounce: ReturnType<typeof setTimeout> | null = null;
    watch(`${cwd}/${configFile}`, () => {
      if (debounce) clearTimeout(debounce);
      debounce = setTimeout(async () => {
        console.log('\n[manic] config changed, restarting...\n');
        proc.kill();
        // Re-import config fresh (bust module cache via timestamp)
        const mod = await import(`${cwd}/${configFile}?t=${Date.now()}`);
        config = mod.default ?? mod;
        proc = await spawn(config);
      }, 100);
    });
  }

  const cleanup = (): void => {
    proc.kill();
    process.exit();
  };

  process.on('SIGINT', cleanup);
  process.on('SIGTERM', cleanup);

  await proc.exited;
}
