import { loadConfig } from '../../config';

interface DevOptions {
  port?: number;
  network?: boolean;
}

export async function dev({ port, network }: DevOptions): Promise<void> {
  const config = await loadConfig();
  const finalPort = port ?? config.server?.port ?? 6070;
  const host = network ? '0.0.0.0' : 'localhost';
  const env = {
    ...process.env,
    PORT: finalPort.toString(),
    HOST: host,
    NETWORK: network ? 'true' : 'false',
  };

  // Collect bunfig snippets from plugins and write bunfig.toml.
  // Merge all [serve.static] plugins into a single section.
  const serveStaticPlugins: string[] = [];
  const otherSnippets: string[] = [];

  for (const plugin of config.plugins ?? []) {
    if (!plugin.bunfig) continue;
    const match = plugin.bunfig.match(/\[serve\.static\]\s*\nplugins\s*=\s*\[([^\]]+)\]/);
    if (match) {
      const names = match[1].split(',').map(s => s.trim()).filter(Boolean);
      serveStaticPlugins.push(...names);
    } else {
      otherSnippets.push(plugin.bunfig);
    }
  }

  const sections: string[] = ['# Auto-generated by manic dev — do not edit'];
  if (serveStaticPlugins.length) {
    sections.push(`[serve.static]\nplugins = [${serveStaticPlugins.join(', ')}]`);
  }
  sections.push(...otherSnippets);

  if (sections.length > 1) {
    await Bun.write(`${process.cwd()}/bunfig.toml`, sections.join('\n\n') + '\n');
  }

  const preloads = (config.plugins ?? [])
    .flatMap(p => p.preload ? ['--preload', p.preload] : []);

  const proc = Bun.spawn(['bun', '--watch', ...preloads, '~manic.ts'], {
    stdout: 'inherit',
    stderr: 'inherit',
    stdin: 'inherit',
    env,
  });

  const cleanup = (): void => {
    proc.kill();
    process.exit();
  };

  process.on('SIGINT', cleanup);
  process.on('SIGTERM', cleanup);

  await proc.exited;
}
