import { Hono } from 'hono';
import { existsSync, writeFileSync, readFileSync } from 'fs';
import { join, isAbsolute } from 'path';

/**
 * Loads API routes from the app/api directory and creates a Hono application.
 *
 * Scans for .ts, .tsx, and .js files in app/api.
 * Each file with a default export becomes an API route.
 * Supports Hono apps, plain handlers, and dynamic route segments [param].
 *
 * @param apiDir - Directory containing API routes (default: "app/api")
 * @returns Hono app, registered routes, and OpenAPI spec
 * @see https://www.manicjs.tech/docs/api/plugin-loaders/api-loader-plugin#behavior
 *
 * @example
 * // Basic usage - loads from app/api
 * const { app, routes, openApiSpec } = await apiLoaderPlugin();
 *
 * @example
 * // Custom API directory
 * const { app, routes } = await apiLoaderPlugin('server/api');
 *
 * @example
 * // Using in ~manic.ts
 * const { apiApp } = await apiLoaderPlugin('app/api');
 * // apiApp is a Hono app with all routes registered
 */
export const apiLoaderPlugin = async (apiDir: string = 'app/api') => {
  const app = new Hono().basePath('/api');
  const routes: string[] = [];
  const apiRoot = isAbsolute(apiDir) ? apiDir : join(process.cwd(), apiDir);

  if (!existsSync(apiRoot))
    return { app, routes, openApiSpec: buildSpec(app, routes) };

  const glob = new Bun.Glob('**/*.{ts,tsx,js}');
  const rawFiles: string[] = [];
  for await (const file of glob.scan({ cwd: apiRoot })) rawFiles.push(file);

  const files = rawFiles.filter(file => {
    const parts = file.split('/');
    return !parts.some(
      part =>
        part.startsWith('~') || part.startsWith('_') || part.startsWith('.')
    );
  });

  const imports: string[] = [];
  const mounts: string[] = [];

  await Promise.all(
    files.map(async file => {
      try {
        const mod = await import(join(apiRoot, file));
        if (!mod.default) return;

        const routePath = (
          '/' +
          file
            .replace(/\.(?:tsx?|js)$/, '')
            .replace(/\/index$/, '')
            .replace(/^index$/, '')
        )
          .replace(/\/+/g, '/')
          .replace(/\[([^\]]+)\]/g, ':$1');

        routes.push(`/api${routePath === '/' ? '' : routePath}`);

        const h = mod.default;
        // Hono instance has .fetch; plain functions don't
        if (typeof h.fetch === 'function') {
          app.route(routePath, h);
        } else if (typeof h === 'function') {
          app.all(routePath, c => h(c));
        }

        // Prepare RPC generation
        const cleanPath = file.replace(/\.(?:tsx?|js)$/, '');
        const importPath = `./${cleanPath}`;
        const safeName =
          'route_' +
          cleanPath.replace(/\/index$/, '').replace(/[^a-zA-Z0-9_]/g, '_');
        imports.push(`import ${safeName} from '${importPath}';`);

        const mountPath = routePath === '/' ? '' : routePath;
        if (typeof h.fetch === 'function') {
          mounts.push(`  .route('${mountPath}', ${safeName})`);
        } else if (typeof h === 'function') {
          mounts.push(`  .all('${mountPath}', ${safeName})`);
        }
      } catch (err) {
        console.error(`[Manic API] Failed to load ${file}:`, err);
      }
    })
  );

  // Generate ~rpc.generated.ts so apps get Hono RPC types automatically.
  // Files prefixed with "~" are ignored by the API scanner and should not be
  // edited by users.
  if (files.length > 0) {
    const generatedContent = `// Auto-generated by Manic. Do not edit.
// This file is regenerated from app/api/**/index.ts during dev/build.
import { Hono } from 'hono';
${imports.sort().join('\n')}

export const app = new Hono()
${mounts.sort().join('\n')};

export type AppType = typeof app;
`;

    const generatedPath = join(apiRoot, '~rpc.generated.ts');
    let existingContent = '';
    if (existsSync(generatedPath)) {
      try {
        existingContent = readFileSync(generatedPath, 'utf-8');
      } catch {}
    }
    if (existingContent !== generatedContent) {
      writeFileSync(generatedPath, generatedContent, 'utf-8');
    }
  }

  return { app, routes, openApiSpec: buildSpec(app, routes) };
};

function buildSpec(app: any, registeredRoutes: string[]) {
  const paths: Record<string, any> = {};
  // Use the registered routes array which already includes the /api prefix,
  // rather than app.routes which stores paths relative to the basePath.
  for (const route of registeredRoutes) {
    const oaPath = route.replace(/:([^/]+)/g, '{$1}');
    if (!paths[oaPath]) paths[oaPath] = {};
    paths[oaPath]['get'] = {
      responses: { 200: { description: 'OK' } },
    };
  }
  return {
    openapi: '3.0.0',
    info: { title: 'Manic API', version: '1.0.0' },
    paths,
  };
}
